name: s1_coursework_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=2.2.3
  - matplotlib=3.9.2
  - scipy=1.14.1
  - seaborn=0.13.2
  - ipykernel=6.29.5
  - ipython=8.29.0
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - notebook  
  - numba=0.60.0
  - iminuit=2.30.1
  - tqdm=4.67.1
  - pip=24.2
  - pip:
    - sweights==1.6.0
    - uncertainties==3.2.2
    - numba-stats==1.10.0